import type { Chapter } from "@/types/chapter";

type ChapterLoader = () => Promise<{ default: Chapter }>;

export const nextChapters: Record<string, ChapterLoader> = {
  "01-what-is-nextjs": () => import("./01-what-is-nextjs"),
  "02-project-setup": () => import("./02-project-setup"),
  "03-file-based-routing": () => import("./03-file-based-routing"),
  "04-layouts-and-templates": () => import("./04-layouts-and-templates"),
  "05-navigation": () => import("./05-navigation"),
  "06-loading-error-ui": () => import("./06-loading-error-ui"),
  "07-server-components": () => import("./07-server-components"),
  "08-client-components": () => import("./08-client-components"),
  "09-server-client-composition": () => import("./09-server-client-composition"),
  "10-server-actions": () => import("./10-server-actions"),
  "11-data-fetching": () => import("./11-data-fetching"),
  "12-caching": () => import("./12-caching"),
  "13-revalidation": () => import("./13-revalidation"),
  "14-streaming-suspense": () => import("./14-streaming-suspense"),
  "15-dynamic-routes": () => import("./15-dynamic-routes"),
  "16-route-groups-parallel": () => import("./16-route-groups-parallel"),
  "17-intercepting-routes": () => import("./17-intercepting-routes"),
  "18-middleware": () => import("./18-middleware"),
  "19-internationalization": () => import("./19-internationalization"),
  "20-styling": () => import("./20-styling"),
  "21-image-optimization": () => import("./21-image-optimization"),
  "22-font-optimization": () => import("./22-font-optimization"),
  "23-metadata-seo": () => import("./23-metadata-seo"),
  "24-performance": () => import("./24-performance"),
  "25-authentication": () => import("./25-authentication"),
  "26-authorization": () => import("./26-authorization"),
  "27-env-security": () => import("./27-env-security"),
  "28-route-handlers": () => import("./28-route-handlers"),
  "29-database-integration": () => import("./29-database-integration"),
  "30-external-api": () => import("./30-external-api"),
  "31-testing": () => import("./31-testing"),
  "32-deployment": () => import("./32-deployment"),
  "33-pages-router": () => import("./33-pages-router"),
  "34-large-scale-architecture": () => import("./34-large-scale-architecture"),
  "35-migration-patterns": () => import("./35-migration-patterns"),
};
