import type { Chapter } from "@/types/chapter";

type ChapterLoader = () => Promise<{ default: Chapter }>;

export const typescriptChapters: Record<string, ChapterLoader> = {
  "01-what-is-typescript": () => import("./01-what-is-typescript"),
  "02-basic-types": () => import("./02-basic-types"),
  "03-type-inference": () => import("./03-type-inference"),
  "04-functions": () => import("./04-functions"),
  "05-objects-and-interfaces": () => import("./05-objects-and-interfaces"),
  "06-type-alias-vs-interface": () => import("./06-type-alias-vs-interface"),
  "07-union-intersection": () => import("./07-union-intersection"),
  "08-type-narrowing": () => import("./08-type-narrowing"),
  "09-discriminated-unions": () => import("./09-discriminated-unions"),
  "10-type-assertions": () => import("./10-type-assertions"),
  "11-generics-basics": () => import("./11-generics-basics"),
  "12-generic-constraints": () => import("./12-generic-constraints"),
  "13-generic-patterns": () => import("./13-generic-patterns"),
  "14-generic-inference": () => import("./14-generic-inference"),
  "15-utility-types": () => import("./15-utility-types"),
  "16-mapped-types": () => import("./16-mapped-types"),
  "17-conditional-types": () => import("./17-conditional-types"),
  "18-template-literal-types": () => import("./18-template-literal-types"),
  "19-infer-keyword": () => import("./19-infer-keyword"),
  "20-structural-typing": () => import("./20-structural-typing"),
  "21-type-compatibility": () => import("./21-type-compatibility"),
  "22-declaration-merging": () => import("./22-declaration-merging"),
  "23-module-types": () => import("./23-module-types"),
  "24-classes": () => import("./24-classes"),
  "25-abstract-classes": () => import("./25-abstract-classes"),
  "26-decorators": () => import("./26-decorators"),
  "27-react-component-types": () => import("./27-react-component-types"),
  "28-react-hooks-types": () => import("./28-react-hooks-types"),
  "29-react-event-types": () => import("./29-react-event-types"),
  "30-react-advanced-patterns": () => import("./30-react-advanced-patterns"),
  "31-tsconfig": () => import("./31-tsconfig"),
  "32-strict-mode": () => import("./32-strict-mode"),
  "33-error-handling-patterns": () => import("./33-error-handling-patterns"),
  "34-api-type-patterns": () => import("./34-api-type-patterns"),
  "35-type-driven-development": () => import("./35-type-driven-development"),
};
