import type { Chapter } from "@/types/chapter";

type ChapterLoader = () => Promise<{ default: Chapter }>;

export const reactChapters: Record<string, ChapterLoader> = {
  "19-virtual-dom-reconciliation": () => import("./19-virtual-dom-reconciliation"),
  "20-fiber-architecture": () => import("./20-fiber-architecture"),
  "21-render-commit-phases": () => import("./21-render-commit-phases"),
  "22-batching": () => import("./22-batching"),
  "23-suspense": () => import("./23-suspense"),
  "24-server-components": () => import("./24-server-components"),
  "25-understanding-rerender": () => import("./25-understanding-rerender"),
  "26-react-memo": () => import("./26-react-memo"),
  "27-react-compiler": () => import("./27-react-compiler"),
  "28-code-splitting": () => import("./28-code-splitting"),
  "29-list-virtualization": () => import("./29-list-virtualization"),
  "30-profiler-devtools": () => import("./30-profiler-devtools"),
  "31-rendering-optimization-patterns": () => import("./31-rendering-optimization-patterns"),
  "32-state-management-overview": () => import("./32-state-management-overview"),
  "33-context-api-advanced": () => import("./33-context-api-advanced"),
  "34-redux-toolkit-basics": () => import("./34-redux-toolkit-basics"),
  "35-redux-toolkit-advanced": () => import("./35-redux-toolkit-advanced"),
  "36-zustand": () => import("./36-zustand"),
  "37-state-management-comparison": () => import("./37-state-management-comparison"),
  "38-react-router-basics": () => import("./38-react-router-basics"),
  "39-react-router-advanced": () => import("./39-react-router-advanced"),
  "40-routing-patterns": () => import("./40-routing-patterns"),
  "41-data-fetching-patterns": () => import("./41-data-fetching-patterns"),
  "42-react-query": () => import("./42-react-query"),
  "43-react-query-advanced": () => import("./43-react-query-advanced"),
  "44-useoptimistic": () => import("./44-useoptimistic"),
  "45-swr-comparison": () => import("./45-swr-comparison"),
  "46-testing-fundamentals": () => import("./46-testing-fundamentals"),
  "47-react-testing-library": () => import("./47-react-testing-library"),
  "48-component-test-patterns": () => import("./48-component-test-patterns"),
  "49-hook-testing": () => import("./49-hook-testing"),
  "50-e2e-testing": () => import("./50-e2e-testing"),
  "51-component-design-principles": () => import("./51-component-design-principles"),
  "52-compound-component": () => import("./52-compound-component"),
  "53-render-props-hoc": () => import("./53-render-props-hoc"),
  "54-container-presentational": () => import("./54-container-presentational"),
  "55-error-boundary": () => import("./55-error-boundary"),
  "56-folder-structure": () => import("./56-folder-structure"),
  "57-large-scale-architecture": () => import("./57-large-scale-architecture"),
  "58-react-ecosystem-future": () => import("./58-react-ecosystem-future"),
};
