import type { Chapter } from "@/types/chapter";

type ChapterLoader = () => Promise<{ default: Chapter }>;

export const jsChapters: Record<string, ChapterLoader> = {
  "01-var-let-const": () => import("./01-var-let-const"),
  "02-data-types": () => import("./02-data-types"),
  "03-operators": () => import("./03-operators"),
  "04-type-coercion": () => import("./04-type-coercion"),
  "05-control-flow": () => import("./05-control-flow"),
  "06-function-definition": () => import("./06-function-definition"),
  "07-first-class-object": () => import("./07-first-class-object"),
  "08-arrow-function": () => import("./08-arrow-function"),
  "09-scope": () => import("./09-scope"),
  "10-lexical-scope": () => import("./10-lexical-scope"),
  "11-execution-context": () => import("./11-execution-context"),
  "12-closure": () => import("./12-closure"),
  "13-object-literal": () => import("./13-object-literal"),
  "14-this-binding": () => import("./14-this-binding"),
  "15-constructor": () => import("./15-constructor"),
  "16-prototype": () => import("./16-prototype"),
  "17-prototype-chain": () => import("./17-prototype-chain"),
  "18-class": () => import("./18-class"),
  "19-built-in-objects": () => import("./19-built-in-objects"),
  "20-wrapper-objects": () => import("./20-wrapper-objects"),
  "21-array-hof": () => import("./21-array-hof"),
  "22-map-set": () => import("./22-map-set"),
  "23-regexp": () => import("./23-regexp"),
  "24-string-number-math-date": () => import("./24-string-number-math-date"),
  "25-event-loop": () => import("./25-event-loop"),
  "26-callback-pattern": () => import("./26-callback-pattern"),
  "27-promise": () => import("./27-promise"),
  "28-async-await": () => import("./28-async-await"),
  "29-microtask-macrotask": () => import("./29-microtask-macrotask"),
  "30-iterable": () => import("./30-iterable"),
  "31-generator": () => import("./31-generator"),
  "32-symbol": () => import("./32-symbol"),
  "33-module-system": () => import("./33-module-system"),
  "34-strict-mode": () => import("./34-strict-mode"),
  "35-error-handling": () => import("./35-error-handling"),
  "36-garbage-collection": () => import("./36-garbage-collection"),
  "37-memory-leak": () => import("./37-memory-leak"),
  "38-debounce-throttle": () => import("./38-debounce-throttle"),
  "39-dom-structure": () => import("./39-dom-structure"),
  "40-event-bubbling-capturing": () => import("./40-event-bubbling-capturing"),
  "41-event-delegation": () => import("./41-event-delegation"),
  "42-browser-rendering": () => import("./42-browser-rendering"),
  "43-proxy-reflect": () => import("./43-proxy-reflect"),
  "44-design-patterns": () => import("./44-design-patterns"),
  "45-functional-programming": () => import("./45-functional-programming"),
};
